server:
  port: 8081
spring:
  application:
    name: technical-test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2 console
  jpa:
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
    show-sql: true
security:
  jwt:
    client-id: Postman
    client-secret: 123456
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: PostmanRs
logging:
  level:
    root: INFO
    org:
      springframework:
        web: TRACE
        security: TRACE
        oauth2: TRACE